image: node:latest

stages:
  - build
  - deploy

build:
  script:
    - npm install
    - npm run build
    - mv build public
  artifacts:
    paths:
      - public

deploy:
  script:
    - echo "Deployment complete!"
